### ISSUE TITLE
Translate book section

### ISSUE THREAD

**Issue by adielcristo** [adielcristo/composer-doc-pt-br#11]
- [x] #3 /doc/00-intro.md
- [x] #4 /doc/01-basic-usage.md
- [x] #5 /doc/02-libraries.md
- [x] #6 /doc/03-cli.md
- [x] #7 /doc/04-schema.md
- [x] #8 /doc/05-repositories.md
- [x] #9 /doc/06-config.md
- [x] #10 /doc/07-community.md
